### ISSUE TITLE
과제3 test 관련

### ISSUE THREAD

**Issue by freor** [snu-sf-class/pp201602#52]
안녕하세요
과제3 run 시에 다음과 같은 오류가 떠서 문의드립니다.
Test.scala의 42, 44 줄에 type mismatch가 뜹니다.
어찌 해결해야 할까요??

감사합니다.

**Comment by alxest** [comment]
조교에게 도움을 기대할 때는 *반드시* submission id를 알려주셔야 합니다.

**Comment by alxest** [comment]
컴파일러 에러 메세지를 그대로 보여주는 것인데, 에러 메세지만 보고는 해결이 불가능한가요?

**Comment by iwill231** [comment]
저도 지금 같은 문제를 겪고 있는데 Test.scala 에서 발생하는거고 제가 보기에는 문제 없어 보여서 에러 메시지만 보고는 해결이 불가능합니다.

**Comment by alxest** [comment]
@iwill231 과제 제출 서버에서 뜨는 에러인가요? 그러면 submission id를 알려주세요...

**Comment by iwill231** [comment]
제출 서버에서 뜨는 에러가 아니라 인텔리제이 IDEA에서 과제를 한 다으메 sbt run을 했을 때 뜨는 에러입니다.

**Comment by alxest** [comment]
1. 문제 없이 돌아가는 구현이 있습니다.
2. 이 글에 적힌 정보만으로는 도움을 드릴 방법이 없습니다. submit 한 후에 submission id를 알려주세요.

**Comment by freor** [comment]
type mismatch warning 이 있으나
코드를 고쳤더니 문제 없이 돌아가는 군요...
코드 문제인것 같습니다. 죄송합니다.

**Comment by Gwangwon-Choi** [comment]
Submission 709 for Assignment 03입니다. 
같은문제를 겪고있는데 뭐가 잘못된 건지 몰라서 올립니다. 제출서버에서는 이상없이 제출이됩니다.

**Comment by alxest** [comment]
@Gwangwon-Choi 
```
[youngju.song@cn04]~/SNU/4/pp201602/hw/03% sbt run
[info] Loading global plugins from /home/youngju.song/.sbt/0.13/plugins
[info] Loading project definition from /home/youngju.song/SNU/4/pp201602/hw/03/project
[info] Set current project to polymorphism (in build file:/home/youngju.song/SNU/4/pp201602/hw/03/)
[info] Compiling 3 Scala sources to /home/youngju.song/SNU/4/pp201602/hw/03/target/scala-2.10/classes...
[warn] /home/youngju.song/SNU/4/pp201602/hw/03/src/main/scala/submission/Main.scala:69: match may not be exhaustive.
[warn] It would fail on the following input: None
[warn]             pop(stk_2) match {
[warn]                ^
[warn] one warning found
[info] Running submission.Test 
Test For Stack Passed
Test For Queue Passed
[error] (run-main-0) java.lang.AssertionError: assertion failed
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:165)
        at submission.Test$$anonfun$2.apply$mcVI$sp(Test.scala:44)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
        at submission.Test$delayedInit$body.apply(Test.scala:43)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at submission.Test$.main(Test.scala:4)
        at submission.Test.main(Test.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 4 s, completed Oct 17, 2016 5:16:35 PM
```

**Comment by Gwangwon-Choi** [comment]
똑같이뜹니다. Test.scala:42랑 Test.scala:44에서 Type mismatching이 된다고 해서 스켈레톤만 다시 갖다놨는데도 똑같은 오류가 있습니다.

**Comment by alxest** [comment]
- 저 메세지 어디에 `Test.scala:42랑 Test.scala:44에서 Type mismatching이 된다`는 말이 있나요?
- 저는 스켈레톤 그대로에서 sbt compile 돌리면 아래와 같이 뜹니다.
```
[youngju.song@cn04]~/SNU/4/pp201602/hw/03% sbt compile
[info] Loading global plugins from /home/youngju.song/.sbt/0.13/plugins
[info] Loading project definition from /home/youngju.song/SNU/4/pp201602/hw/03/project
[info] Set current project to polymorphism (in build file:/home/youngju.song/SNU/4/pp201602/hw/03/)
[info] Compiling 3 Scala sources to /home/youngju.song/SNU/4/pp201602/hw/03/target/scala-2.10/classes...
[success] Total time: 3 s, completed Oct 17, 2016 5:24:16 PM
```

**Comment by alxest** [comment]
애초에 type mismatch 가 있으면 실행이 안되야죠... 위 에러 메세지는 실행이 되고 런타임에 에러가 뜬겁니다. 구현의 문제에요.

**Comment by Gwangwon-Choi** [comment]
알겠습니다. 다시해보겠습니다. 

감사합니다.

**Comment by alxest** [comment]
@Gwangwon-Choi 
- 다시 묻습니다. 메세지가 똑같이 뜬다고 하셨는데, 어디에 `Test.scala:42랑 Test.scala:44에서 Type mismatching이 된다`는 말이 있나요? 
본인 창에서는 에러가 다르게 뜨는건가요? 아니면 에러 메세지를 읽지 않고 질문한건가요?
- 스켈레톤만 갖다놔도 에러가 뜨는 환경이 저는 재생산이 안되니까, 재생산되는 상태 그대로 연구실에 직접 방문해서 보여주세요.

**Comment by Gwangwon-Choi** [comment]
![image](https://cloud.githubusercontent.com/assets/22405968/19430884/08892496-9491-11e6-80ad-bbf66a9ef769.png)

**Comment by alxest** [comment]
확인 결과 이건 IntelliJ의 버그입니다....

**Comment by Gwangwon-Choi** [comment]
감사합니다! 다시구현해보니까 문구는 떠도 실행까지 잘 됩니다. 
설명 잘 해주셔서 감사합니다.

**Comment by iwill231** [comment]
아 이제야 확인합니다. 답변 감사합니다.
